### ISSUE TITLE
Could not find 'wandb_habitat/habitat_vc'

### ISSUE THREAD

**Issue by yairshp** [facebookresearch/eai-vc#12]
I am trying to train and evaluate both habitat benchmarks (objectnav and imagenav). after following all installation instructions, i get this error when trying the following commands:
```python run_habitat_vc.py --config-name=config_imagenav -m```
```python run_habitat_vc.py --config-name=config_objectnav_il_frozen WANDB.name=Objectnav_first_experiment model=vc1_vitl -m```

I get the same error for both commands (the output is after setting the HYDRA_FULL_ERROR to 1):
```
/home/lab/yairshp/instance_image_nav/eai-vc/third_party/habitat-lab/habitat/utils/visualizations/maps.py:25: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  AGENT_SPRITE = imageio.imread(
pybullet build time: May  2 2023 05:58:25
run_habitat_vc.py:26: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="configs", config_name="config_imagenav")
Traceback (most recent call last):
  File "run_habitat_vc.py", line 111, in <module>
    main()
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 143, in multirun
    cfg = self.compose_config(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 253, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 745, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 715, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 356, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 457, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 573, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 520, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 488, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 799, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: In 'config_imagenav': Could not find 'wandb_habitat/habitat_vc'

Config search path:
	provider=vc_models-plugin, path=pkg://vc_models.conf
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///home/lab/yairshp/instance_image_nav/eai-vc/cortexbench/habitat_vc/configs
	provider=classy_vision, path=pkg://classy_vision.hydra.conf
	provider=schema, path=structured://
```

It seems like there is no wandb_habitat dir in the configs dir. when removing the relevant line from the configs/config_imagenav.yaml, I get the following error:
```
/home/lab/yairshp/instance_image_nav/eai-vc/third_party/habitat-lab/habitat/utils/visualizations/maps.py:25: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  AGENT_SPRITE = imageio.imread(
pybullet build time: May  2 2023 05:58:25
run_habitat_vc.py:26: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="configs", config_name="config_imagenav")
Traceback (most recent call last):
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 153, in multirun
    sweeper = Plugins.instance().instantiate_sweeper(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/core/plugins.py", line 140, in instantiate_sweeper
    sweeper.setup(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 90, in setup
    self.launcher = Plugins.instance().instantiate_launcher(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/core/plugins.py", line 155, in instantiate_launcher
    launcher = self._instantiate(config.hydra.launcher)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/core/plugins.py", line 112, in _instantiate
    plugin = instantiate(config=config, _target_=clazz)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 220, in instantiate
    OmegaConf.resolve(config)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 785, in resolve
    omegaconf._impl._resolve(cfg)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/_impl.py", line 40, in _resolve
    _resolve_container_value(cfg, k)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/_impl.py", line 14, in _resolve_container_value
    resolved = node._dereference_node()
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 246, in _dereference_node
    node = self._dereference_node_impl(throw_on_resolution_failure=True)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 277, in _dereference_node_impl
    return parent._resolve_interpolation_from_parse_tree(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 921, in accept
    return visitor.visitInterpolationNode(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 158, in visitInterpolationNode
    return self.node_interpolation_callback(inter_key, self.memo)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 745, in node_interpolation_callback
    return self._resolve_node_interpolation(inter_key=inter_key, memo=memo)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 664, in _resolve_node_interpolation
    parent, last_key, value = root_node._select_impl(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 531, in _select_impl
    value = root._maybe_resolve_interpolation(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 719, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 921, in accept
    return visitor.visitInterpolationNode(self)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 158, in visitInterpolationNode
    return self.node_interpolation_callback(inter_key, self.memo)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 745, in node_interpolation_callback
    return self._resolve_node_interpolation(inter_key=inter_key, memo=memo)
  File "/cortex/users/yairshp/miniconda3/envs/eai-vc/lib/python3.8/site-packages/omegaconf/base.py", line 676, in _resolve_node_interpolation
    raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'WANDB.name' not found
```

**Comment by TeleeMa** [comment]
I also encountered the same problem. Have you solved it? @yairshp

**Comment by KennyYao2001** [comment]
I also encountered the same problem. Any updates? @yairshp

**Comment by xwen99** [comment]
Their gitignore file just ignored these config files:
https://github.com/facebookresearch/eai-vc/blob/76fe35e87b1937168f1ec4b236e863451883eaf3/cortexbench/habitat_vc/.gitignore#L20

To run experiments you may need to recreate them, I suggest referencing those in habitat2_vc

**Comment by ykarmesh** [comment]
Sorry about this. This PR should solve the issue: https://github.com/facebookresearch/eai-vc/pull/21
